name: Run Seavision Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
name: Run ADS-B Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: windows-latest  # Use GitHub-hosted Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install dependencies

      - name: Run ADS-B Script
        run: |
          python "adsb.py"  # Runs your Python script

      - name: Commit and push changes to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add docs/ADSB.geojson  # Add the ADSB.geojson file (adjust if needed)
          git commit -m "Update ADSB.geojson with new ADS-B data"
          git push https://github.com/alexvera626/ADSB.git HEAD:main  # Push to the 'main' branch of the 'ADSB' repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication
