name: Run Seavision Script

on:
  schedule:
    - cron: '*/5 * * * *'  # This means the script will run every 5 minutes.
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # This runs on the latest version of Ubuntu (Linux)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8 (or another version if needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install dependencies (e.g., requests)

      - name: Run Seavision Data Script
        run: |
          python "Seavision Data.py"  # Runs your Python script (Seavision_Data.py)

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add docs/SeaVision_Data.geojson
          git commit -m "Update GeoJSON file"
          git push https://github.com/alexvera626/svision.git HEAD:main
        env:
          GITHUB_TOKEN: ${{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}}  # Correct token reference
