name: Run Seavision Script

on:
  schedule:
    - cron: '*/5 * * * *'  # This means the script will run every 5 minutes.
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # This runs on the latest version of Ubuntu (Linux)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8 (or another version if needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install dependencies (e.g., requests)

      - name: Run Seavision Data Script
        run: |
          python "Seavision Data.py"  # Runs your Python script (Seavision Data.py)

      - name: Move GeoJSON to docs folder
        run: |
          mkdir -p docs  # Create the docs folder if it doesn't exist
          mv SeaVision_Data.geojson docs/SeaVision_Data.geojson  # Move the file into docs folder

      - name: Commit and push GeoJSON to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/SeaVision_Data.geojson
          git commit -m "Update GeoJSON file"
          git push origin main  # Push the changes back to the GitHub repository
