name: Run Seavision Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu (Linux)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install dependencies

      - name: Run Seavision Data Script
        run: |
          python "Seavision Data.py"  # Runs your Python script

      - name: Commit and push changes to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add docs/SeaVision_Data.geojson docs/SeaVision_Data.csv  # Add the GeoJSON and CSV files
          git commit -m "Update GeoJSON and CSV files with new vessel data"
          git push https://github.com/alexvera626/svision.git HEAD:main  # Push to the 'main' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication
